apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: slash-command-parser
  labels:
    knative.dev/type: "function"
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/botless/parser/cmd/slash/
            env:
            - name: TARGET
              value: "http://parser-out-channel-kx7fg.default.svc.cluster.local/" # <---------------   TODO: update this.
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: slash-command-parser
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: slack-in
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: slash-command-parser
---
# Events will be sent to out of the parser on parser-out
apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: parser-out
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory-channel
